/* Generated By:JJTree: Do not edit this line. AST_PredicateExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_PredicateExpression extends SimpleNode {
  public AST_PredicateExpression(int id) {
    super(id);
  }

  public AST_PredicateExpression(CommandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3b8e11723668e712f27e74456a4d45c (do not edit this line) */
