/* Generated By:JJTree: Do not edit this line. AST_EvalExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_EvalExpr extends SimpleNode {
  public AST_EvalExpr(int id) {
    super(id);
  }

  public AST_EvalExpr(CommandParser p, int id) {
    super(p, id);
  }
  
  public String script;

}
/* JavaCC - OriginalChecksum=fd4a3c16c63c691fcc89d660ee575aee (do not edit this line) */
