/* Generated By:JJTree: Do not edit this line. AST_ComparisonExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_ComparisonExpression extends SimpleNode {
  public AST_ComparisonExpression(int id) {
    super(id);
  }

  public AST_ComparisonExpression(CommandParser p, int id) {
    super(p, id);
  }
  
  
  protected Expression expr = new Expression();
}
/* JavaCC - OriginalChecksum=7eedfcc2765c3247a645bed1085b6187 (do not edit this line) */
