/* Generated By:JJTree: Do not edit this line. AST_Regex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_Regex extends SimpleNode {
  public AST_Regex(int id) {
    super(id);
  }

  public AST_Regex(CommandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff22ed9791dc1ff157497ab66d6f5836 (do not edit this line) */
