/* Generated By:JJTree: Do not edit this line. AST_AndExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_AndExpr extends SimpleNode {
  public AST_AndExpr(int id) {
    super(id);
  }

  public AST_AndExpr(CommandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ba6f1cd29aaf6f33f24b2f16c1eaaf4 (do not edit this line) */
