/* Generated By:JJTree: Do not edit this line. AST_OrExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_OrExpr extends SimpleNode {
  public AST_OrExpr(int id) {
    super(id);
  }

  public AST_OrExpr(CommandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3ec20accd73822cc748d70821a73156 (do not edit this line) */
