/* Generated By:JJTree: Do not edit this line. AST_SearchOption.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

import com.everdata.command.Option;

public
class AST_SearchOption extends SimpleNode {
  public AST_SearchOption(int id) {
    super(id);
  }

  public AST_SearchOption(CommandParser p, int id) {
    super(p, id);
  }
  
  protected Option opt = new Option();
  
}
/* JavaCC - OriginalChecksum=adb3136c09c654789d18cd772f208abd (do not edit this line) */
