/* Generated By:JJTree: Do not edit this line. AST_TopOption.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

import com.everdata.command.Option;

public
class AST_TopOption extends SimpleNode {
  public AST_TopOption(int id) {
    super(id);
  }

  public AST_TopOption(CommandParser p, int id) {
    super(p, id);
  }
  
  protected Option opt = new Option();
  
}
/* JavaCC - OriginalChecksum=58f509b50d86058e0576e29411881d35 (do not edit this line) */
