/* Generated By:JJTree: Do not edit this line. AST_UnaryExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public class AST_UnaryExpr extends SimpleNode {
	boolean isNot = false;

	public AST_UnaryExpr(int id) {
		super(id);
	}

	public AST_UnaryExpr(CommandParser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=9c5b36e4a7f4d776543a0f79ea9b64ba (do not edit this
 * line)
 */
