/* Generated By:JJTree: Do not edit this line. AST_Sort.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

import java.util.ArrayList;

public class AST_Sort extends SimpleNode {
	public AST_Sort(int id) {
		super(id);
	}

	public AST_Sort(CommandParser p, int id) {
		super(p, id);
	}
	
	public ArrayList<String> sortFields = new ArrayList<String>();
		
	public boolean desc = false;
	
	public int count = 10000;

}
/* JavaCC - OriginalChecksum=6bc3e0dc0cc9078825f2531aed0fbbf4 (do not edit this line) */
