/* Generated By:JJTree: Do not edit this line. AST_Delete.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_Delete extends SimpleNode {
  public AST_Delete(int id) {
    super(id);
  }

  public AST_Delete(CommandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86f701e98ac1441bed480141c4f146dc (do not edit this line) */
