/* Generated By:JJTree: Do not edit this line. AST_FieldExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public
class AST_FieldExpr extends SimpleNode {
  public AST_FieldExpr(int id) {
    super(id);
  }

  public AST_FieldExpr(CommandParser p, int id) {
    super(p, id);
  }
  
  public int type;
  public String field;

}
/* JavaCC - OriginalChecksum=c162b35dd9b97b3ae37931b754c4a582 (do not edit this line) */
