/* Generated By:JJTree: Do not edit this line. AST_TermExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

public class AST_TermExpression extends SimpleNode {
	
	public final static int PHRASE = 1;
	public final static int TERM = 2;

	public AST_TermExpression(int id) {
		super(id);
	}

	public AST_TermExpression(CommandParser p, int id) {
		super(p, id);
	}
	
	int type;
	String term;
}
/*
 * JavaCC - OriginalChecksum=e8f812fdfd78761973e6eff986241cd1 (do not edit this
 * line)
 */
