/* Generated By:JJTree: Do not edit this line. AST_StatsFunc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.everdata.parser;

import com.everdata.command.Function;

public
class AST_StatsFunc extends SimpleNode {
  public AST_StatsFunc(int id) {
    super(id);
  }

  public AST_StatsFunc(CommandParser p, int id) {
    super(p, id);
  }
  
  public Function func = new Function();

}
/* JavaCC - OriginalChecksum=f227121067e732204b344960e1df54a9 (do not edit this line) */
