/* Generated By:JavaCC: Do not edit this line. CommandParserTreeConstants.java Version 5.0 */
package com.everdata.parser;

public interface CommandParserTreeConstants
{
  public int JJT_START = 0;
  public int JJT_JOIN = 1;
  public int JJT_SORT = 2;
  public int JJT_REGEX = 3;
  public int JJT_STATS = 4;
  public int JJT_STATSFUNC = 5;
  public int JJT_EVALEXPR = 6;
  public int JJT_DELETE = 7;
  public int JJT_TOP = 8;
  public int JJT_IDENTLIST = 9;
  public int JJT_TOPOPTION = 10;
  public int JJT_BYIDENTLIST = 11;
  public int JJT_SEARCH = 12;
  public int JJT_OREXPR = 13;
  public int JJT_ANDEXPR = 14;
  public int JJT_UNARYEXPR = 15;
  public int JJT_SEARCHOPTION = 16;
  public int JJT_PREDICATEEXPRESSION = 17;
  public int JJT_TERMEXPRESSION = 18;
  public int JJT_COMPARISONEXPRESSION = 19;


  public String[] jjtNodeName = {
    "_Start",
    "_Join",
    "_Sort",
    "_Regex",
    "_Stats",
    "_StatsFunc",
    "_EvalExpr",
    "_Delete",
    "_Top",
    "_IdentList",
    "_TopOption",
    "_ByIdentList",
    "_Search",
    "_OrExpr",
    "_AndExpr",
    "_UnaryExpr",
    "_SearchOption",
    "_PredicateExpression",
    "_TermExpression",
    "_ComparisonExpression",
  };
}
/* JavaCC - OriginalChecksum=ee4da42212be56d346b859a6ee8863ae (do not edit this line) */
