/* Generated By:JavaCC: Do not edit this line. CommandParserTreeConstants.java Version 5.0 */
package com.everdata.parser;

public interface CommandParserTreeConstants
{
  public int JJT_START = 0;
  public int JJT_TABLE = 1;
  public int JJT_JOIN = 2;
  public int JJT_SORT = 3;
  public int JJT_REGEX = 4;
  public int JJT_STATS = 5;
  public int JJT_STATSFUNC = 6;
  public int JJT_EVALEXPR = 7;
  public int JJT_DELETE = 8;
  public int JJT_IDENTLIST = 9;
  public int JJT_BYIDENTLIST = 10;
  public int JJT_SEARCH = 11;
  public int JJT_OREXPR = 12;
  public int JJT_ANDEXPR = 13;
  public int JJT_UNARYEXPR = 14;
  public int JJT_SEARCHOPTION = 15;
  public int JJT_PREDICATEEXPRESSION = 16;
  public int JJT_TERMEXPRESSION = 17;
  public int JJT_COMPARISONEXPRESSION = 18;


  public String[] jjtNodeName = {
    "_Start",
    "_Table",
    "_Join",
    "_Sort",
    "_Regex",
    "_Stats",
    "_StatsFunc",
    "_EvalExpr",
    "_Delete",
    "_IdentList",
    "_ByIdentList",
    "_Search",
    "_OrExpr",
    "_AndExpr",
    "_UnaryExpr",
    "_SearchOption",
    "_PredicateExpression",
    "_TermExpression",
    "_ComparisonExpression",
  };
}
/* JavaCC - OriginalChecksum=ac0ad954e97fc550f507838e612d0e06 (do not edit this line) */
